gui: fix template arguments
Fixes macOS compilation aborting due to using QVector without template arguments

../src/gui/navigator_node.cpp:47:10: error: use of class template 'QVector' requires template arguments
                return QVector({FileFormt::EX, FileFormat::TXTEX});
                       ^